package com.gadarts.necromine.editor.desktop;

public enum Events {
	MODE_SET_EDIT,
	MODE_SET_CAMERA,
	REQUEST_TO_SET_EDIT_MODE,
	REQUEST_TO_SET_CAMERA_MODE,
	REQUEST_TO_ROTATE_SELECTED_OBJECT,
	REQUEST_TO_SAVE,
	REQUEST_TO_LOAD,
	TREE_ENTRY_SELECTED
}
