package com.gadarts.necromine.editor.desktop;

public enum Events {
	MODE_SET_EDIT,
	MODE_SET_CAMERA,
	TILE_TOOL_SET,
	ENV_TOOL_SET,
	REQUEST_TO_SET_EDIT_MODE,
	REQUEST_TO_SET_CAMERA_MODE,
	REQUEST_TO_ROTATE_SELECTED_OBJECT,
	REQUEST_TO_SAVE,
	REQUEST_TO_LOAD,
	REQUEST_TO_SET_TILE_TOOL,
	REQUEST_TO_SET_ENV_TOOL,
	REQUEST_TO_OPEN_AMBIENT_LIGHT_DIALOG,
	TREE_ENTRY_SELECTED
}
